XVimProject/XVim

XVim/Info.plist

This adds the UDID of Xcode 6.3 beta. After a build with Xcode, and a restart, Xvim works as expected.
Fixes #685

Add Xcode 6.3 beta support

---

XVim/NSTextStorage+VimOperation.m
XVim/NSTextView+VimOperation.m

This fixes an issue where, when the start of the line is the last
character of the file, there an off by 1 error that would cause shift-o
not to work. `characterAtIndex` expects and index within the bounds of
this string, the passed character index was previously the length of the
string.
This fixes #675

Fix Shift-O on the last line of the file

---

XVim.xcodeproj/project.pbxproj

Basically the current settings supposes that Xcode.app lives in /Applications which may not be true for everybody

Do not hardcode where Xcode lives, derive the paths from DEVELOPER_DIR

---

XVim.xcodeproj/project.pbxproj
XVim/NSTextView+VimOperation.m
XVim/XVimCommandField.m
XVim/XVimCommandLineEvaluator.m
XVim/XVimDefs.h
XVim/XVimEvaluator.m
XVim/XVimExCommand.m
XVim/XVimInsertEvaluator.m
XVim/XVimKeyStroke.h
XVim/XVimKeyStroke.m
XVim/XVimMarkSetEvaluator.m
XVim/XVimMotionEvaluator.m
XVim/XVimNormalEvaluator.m
XVim/XVimNumericEvaluator.m
XVim/XVimRegisterEvaluator.m
XVim/XVimReplaceEvaluator.m
XVim/XVimVisualEvaluator.m

This branch significantly reduces the amount of allocations and selectors called for each keystroke
it has also a couple of fixes:
- b_v_D/b_v_C work better
- single char mode replace with a non printable key doesn't leave you in a bad state anymore (3r<Right>) and does nothing as in vim

Keystrokes

---

XVim/Info.plist

Fixes #707 
Add `A16FF353-8441-459E-A50C-B071F53F51B7` to the `DVTPlugInCompatibilityUUIDs` array.

Add support for Xcode 6.2 (6C131e)

---

Documents/Users/FeatureList.md
XVim.xcodeproj/project.pbxproj
XVim/NSTextView+VimOperation.m
XVim/Test/XVimTester+Jump.m
XVim/XVimExCommand.m
XVim/XVimGActionEvaluator.m
XVim/XVimGMotionEvaluator.m
XVim/XVimMark.h
XVim/XVimMark.m
XVim/XVimMarkSetEvaluator.m
XVim/XVimMarks.h
XVim/XVimMarks.m
XVim/XVimMotion.h
XVim/XVimMotion.m
XVim/XVimMotionEvaluator.h
XVim/XVimMotionEvaluator.m
XVim/XVimNormalEvaluator.m
XVim/XVimVisualEvaluator.m
XVim/XVimWindow.h
XVim/XVimWindow.m

- `CTRL-i`, `CTRL-o` is changed to use jump list but Xcode forward/backward history.
- Xcode forward/backward history jump is assigned to `:njump`, `:pump`
- `jumps`
- Issue #159 and #626 relate.

Add jumplist feature

---

XVim/Info.plist

It seems that the Xcode 6.3 support was merged as a hotfix into `master` without merging back down to `develop`.
Thanks :cactus:

Add Xcode 6.3 support to develop branch

---

Documents/Users/FeatureList.md
README.md
README_jp.md

I changed the link to the relative link. Because this one is simple and is useful for a forked developer.
See also: [Relative links in READMEs - User Documentation](https://help.github.com/articles/relative-links-in-readmes/ "Relative links in READMEs - User Documentation")

Use relative links

---

XVim/XVimExCommand.m
XVim/XVimMarks.m

This marks format is more original vim-like.
I think empty marks should not fill lines.

improve :marks dump format

---

XVim/Info.plist

I haven't fully tested all the Xvim features in Xcode 6.4, but it didn't seem to work without adding the UUID, so I thought I would try and do that.

Add UUID to support Xcode Beta 6.4

---

XVim.xcodeproj/project.pbxproj
XVim/Test/XVimTester+Options.m
XVim/XVimOptions.m

This patch adds support for inverting set options. For example, in vim, you may use:
:set rnu!
to toggle between `:set relativenumber` and `:set norelativenumber`.
I don't see a test case for options so I can't write a test case. I can confirm the following manual tests:
:set rn!               # sets relative number on
:set rn!               # sets relative number off
:set relativenumber!   # sets relative number on
:set relativenumber!   # sets relative number off
:set bc!               # sets blinking cursor on
:set bc!               # sets blinking cursor off
:set clipboard!        # does nothing as `_clipboard` is not a `BOOL`
:set !                 # does nothing

Add support for inverting set options

---

Documents/Users/FeatureList.md
XVim/NSTextView+VimOperation.m
XVim/Test/XVimTester+Jump.m
XVim/Test/XVimTester+Motion.m
XVim/Test/XVimTester+Visual.m
XVim/XVimOptions.h
XVim/XVimOptions.m

This patch adds a `startofline` option to `XVimOptions`. This option follows vim, where it is `on` by default.
When `startofline` is set, whenever `G` or `gg` is used, the cursor will be placed on the first non-blank character of the last or first line respectively.
When `nostartofline` is set, the current cursor column will be preserved.
This patch fixes #742 and is made possible by a patch from @J-Fields
--------
As this patch changes default behaviour, some of the existing tests have been amended to reflect the **correct** intended behaviour. Tests for `set startofline` and `set nostartofline` have been added to `XVimTester+Jump.m`.

Add startofline option (fixes gg in visual mode)

---

XVim/XVim.m

`+ (void)load` call `+ (void)addXVimMenu` delay by *GCD*, but sometimes it still is *nil*. Use notification to get event for finish launching.

sometime menu disappear, fix it

---

XVim/IDEWorkspaceTabController+XVim.h
XVim/IDEWorkspaceTabController+XVim.m
XVim/XVimWindow.m

- Bug fix #711 caret isn't  redrawn in genius mode.
- Improvement for comparison mode.
In version comparison mode when you change window focus the current cursor line number is preserved like the original vimdiff mode.

Improvement Genius mode and comparison mode

---

README.md
XVim/Info.plist

In order to support Xcode 7 GM released on September 9th, 2015, this
commit adds the correct UUID to the DVTPlugInCompatibilityUUIDs array in
the Info.plist. In addition, it highlights this compatibility in the
README.md

Add support for Xcode 7 GM

---

XVim.xcodeproj/project.pbxproj
XVim/NSURL+XVimXcodeModule.h
XVim/NSURL+XVimXcodeModule.m
XVim/XVimExCommand.m

Apple framework like Foundation.framework has Objective-C header file.
When I select class name like 'NSObject' and click 'Jump to Definition' 
Xcode6 show swift file that is converted from Objective-C header file probably.
So I can't open the swift file with the external editor like the MacVim.
This PR make it possible.
While a converted swift file is showed, document URL has 'x-xcode-module' scheme and original Objective-C header file path.
Because I don't know how to convert Objective-C header file to swift header file
I use showing text as is.
I have knowed them by observing Xcode behaviour that is reverse engineeing. 
No documents.  
In bang command while 'x-xcode-module' scheme file is showed,  percent is expanded to 
~/.xvimtmp.swift file. So you can open converted swift module …

Add support swift format module header for bang

---

XVim/Test/XVimTester+Search.m
XVim/XVimMotionEvaluator.m

Only search backwards an extra time if not at the beginning of a word.
The method `searchCurrentWordForward` when parameter `forward` is `NO`
previously skipped a word if the cursor is at the beginning of a word.
Repeatedly invoking `NUMBER` would skip every other word. NB when
searching backward (`QUESTION`) while in the middle of the searched
word, the first match is the word at the cursor. This was incorrectly
compensated for by searching backwards an extra time, regardless of
cursor location in the current word.
- The new test case fails without the fix, and succeeds with the fix.
- Maybe fixes issue #723.

Fix behavior of NUMBER/searchCurrentWordForward (#723)

---

XVim/Info.plist

I don't know if UUID of Xcode 7 GM seed should be added as well, so only add 7.1 beta for my own needs.
UUID of  Xcode 7 GM seed is `<string>0420B86A-AA43-4792-9ED0-6FE0F2B16A13</string>`

Add UUID for Xcode Beta 7.1

---

Documents/Users/FeatureList.md
XVim/NSTextView+VimOperation.m
XVim/Test/XVimTester+Operator.m
XVim/Test/XVimTester+Visual.m
XVim/XVimOptions.h
XVim/XVimOptions.m

- Add option `expandtab` with default YES.
- Use tab instead of spaces in `xvim_shift:right:withMotionPoint:count`
for `right:YES` if `expandtab` is NO.
- Solves issue #795

Implement noexpandtab for `>>`, solve issue #795

---

XVim/IDESourceCodeEditor+XVim.m

On case sensitive system XVim/IDESourceCodeEditor+XVim.m failed to compile with "fatal error: 'NSobject+ExtraData.h' file not found". Note the letter "o" in #import is lowercase, while the "O" in filename is uppercase.

#import typo in XVim/IDESourceCodeEditor+XVim.m

---

XVim/Test/XVimTester+Issues.m
XVim/Test/XVimTester+Operator.m

Currently, if Xcode is set to indent with tabs a few unit tests (that are dependent upon whitespace settings) fail. We now read in the Xcode preferences and base our tests off of that setting.
Note: Although it is easy enough to detect tabs/spaces indentation and although it is easy enough to detect how many spaces are inserted for space indentation, it is not as straightforward to test spaces. The biggest problem is the tabWidth for inserting spaces. This can vary dramatically and since most of our test case strings are hard coded, this is not such an easy task. This makes tab indentation testing look more appealing, actually, in my humble opinion. If we wanted to support various tabWidth's for space indentation, we would need to start generating some of the unit test strings …

XVimProject/XVim#845 Allow whitespace agnostic unit testing

---

Documents/Users/FeatureList.md
XVim/XVimZEvaluator.m

Tried to hook into Xcode's menus whereever possible. Not all of vim's functionality is available in Xcode, so I made due with what I had.
In some cases, I went with what seems to make the most sense rather than strictly adhering to what the user wanted. For example, C-o opens a fold. C-O should open a fold under the cursor recursively. However, Xcode doesn't support this. So, rather than disable the C-O mapping entirely, I defaulted it to C-o instead.

Adding additional z mappings for folding.

---

XVim/NSURL+XVimXcodeModule.h
XVim/NSURL+XVimXcodeModule.m
XVim/XVimExCommand.m

Since 'x-xcode-module' scheme is modified in Xcode7, add support that.
Also swift file path is changed to ~/.xvim/caches/.

Support swift format module header for bang in Xcode7

---

Documents/Users/FeatureList.md
XVim/XVimNormalEvaluator.m

C-] can be used to jump to definition and C-t can be used to jump back. Added in C-t.

Adding some missing keybindings.

---

XVim/Info.plist

Xvim plugin doesn't work after updating Xcode 7.2

Add DVTPlugInCompatibilityUUID of Xcode 7.2

---

Makefile

Right now, the Makefile does not handle the case when the `xcode_path` contains spaces correctly. This pull request fixes that.

fix Makefile when Xcode folder has spaces (e.g. /Applications/Xcode 7)

---

XVim/IDEPlaygroundEditor+XVim.m

Project fails to build due to typo on
case-sensitive filesystems

Fix import typo in IDEPlaygroundEditor+XVim.m

---

XVim/XVimRecordingEvaluator.m

Previously, the Normal mode keymap would always be used while recording,
and for example, typing `q` would cause the recording to stop even when in Insert mode.
Now if the recording evaluator detects that it is in insertion mode,
it will use the correct keymap, and disregard the stop signal.

Use correct keymap when recording macro.

---

XVim/NSTextView+VimOperation.m
XVim/Test/XVimTester+Operator.m

This should fix the auto indent issue.
I just read this part of source code, and `-[XVimDeleteEvaluator motionFixed:]` is the only caller of `-xvim_change:` , so this change may not affect other functions in my opinion.

Fix #769 'cc' and 'S' auto indent issue

---

XVim/XVimCommandLine.m

This is a fix for #893.
While it works cleanly, there's probably a better way of dealing with this. I'm open to discussion either in this Pull Request or in the [original issue](https://github.com/XVimProject/XVim/issues/893). As it stands however, this does fix the issue!

Override command line background colour

---

XVim/NSTextView+VimOperation.m
XVim/Test/XVimTester+TextObject.m

di{,di(,di<,di[ have many bugs.
I fixed a tiny bug of them.

Fix bug wrong cursor pos after di{, di(, di<, di[

---

Makefile

Minor fix. Made the compatibility message in the makefile more easily understood.

grammar fix for compatibility message

---

XVim/DVTSourceTextView+XVim.m

I think the patch fixed both the issue and the bug that the cursor blinks while scrolling.
I checked blinkcursor and non-blinkcursor behavior for DVTSourceTextView and IDEPlaygroundTextView for Xcode7.2.1 and OS X 10.10.5(Yosemite).

Fix #882 Text stretching when scrolling

---

XVim/NSTextStorage+VimOperation.m
XVim/NSTextView+VimOperation.m
XVim/Test/XVimTester+Motion.m
XVim/Test/XVimTester+Visual.m
XVim/XVimGMotionEvaluator.m
XVim/XVimGVisualEvaluator.m

This Pull Requests adds support for backwards end word movement. I intend to mirror the behaviour apparent in Vim, with all its quirks.
- `gE` goes to the end of the previous `WORD`
- `2gE` goes to end of the second-to-last `WORD`
- `ge` goes to the end of the previous `word`
- `2ge` goes to end of the second-to-last `word`
- `vge` selects from the current index to the end of the previous `word`
- `gE` sets the cursor to the beginning of the line if there are no word boundries. See below:
```
// [ ] cursor position
ab[c] def
// Type
gE
// Moves the cursor to the beginning of the line
[a]bc def
```
This fixes #918.

Add implementation of gE / ge

---

XVim/NSTextView+VimOperation.m
XVim/Test/XVimTester+Issues.m

This is a hotfix for issue #251.
I'm unable to get the crash to happen while running tests, so I've had to manually test this using the following steps, using the latest `develop` branch in Xcode 7.3:
1. enter any file
2. hit `gg` to move to beginning of file
3. `V` to enter visual mode
4. hit `G` to move to the end of the file
5. hit `cmd+/` to comment the selected lines (every line in the file)
6. hit `esc` to exit visual mode
7. hit `gg` to move to beginning of file
8. `V` to enter visual mode
9. hit `G` to move to the end of the file
10. hit `cmd+/` to uncomment the selected lines
11. Xcode crashes with an out of bounds error
I experienced this crash when trying to delete a range towards the end of a file, but I'm unable to reproduce in the test environment, perhaps it only occurs …

Hotfix for issue #251

---

XVim/XVimExCommand.m

`:tabprevious` now calls the correct method.
Fixes #1030

:tabp should open the previous tab

---

INSTALL_Xcode8.md

Hello, your re-signing README broke (probably with GitHub's move to commonmark)
So, I fixed it.

Updates the Xcode 8 installation step
